#!/usr/bin/env python3
"""
Offline LUT generator for mind-nerve/mind/luts/*.mind.

Produces deterministic Q16.16 / Q32.32 table values for the five LUT
families used by the native MIND inference path.  Writes pre-populated
MIND source files to mind/luts/ and the smoke-test fixture to
tests/luts_smoke.mind.

Q16.16 encoding: an i64 where value 1.0 == 65536 (1 << 16).
Q32.32 encoding: an i64 where value 1.0 == 2^32 == 4294967296.

All tables are generated with Python float64 arithmetic and rounded
toward negative infinity (floor) to match the truncated-lookup contract
in spec/numerics.md §5.
"""

import math
import os
import random
import struct

# ── constants ──────────────────────────────────────────────────────────────────
Q16_ONE   = 1 << 16          # 65536
Q32_ONE   = 1 << 32          # 4294967296
Q16_MAX   = (1 << 31) - 1    # i64 stored as i64; Q16.16 max representable ~32767.9999
Q16_MIN   = -(1 << 31)
Q32_MAX   = (1 << 63) - 1
Q32_MIN   = -(1 << 63)

REPO_ROOT   = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LUTS_DIR    = os.path.join(REPO_ROOT, "mind", "luts")
TESTS_DIR   = os.path.join(REPO_ROOT, "tests")
TOOLS_DIR   = os.path.join(REPO_ROOT, "tools")

os.makedirs(LUTS_DIR, exist_ok=True)
os.makedirs(TESTS_DIR, exist_ok=True)

# ── helpers ────────────────────────────────────────────────────────────────────

def to_q16(x: float) -> int:
    """Convert float to Q16.16 i64, floor-truncated, clamped to i32 range."""
    raw = math.floor(x * Q16_ONE)
    return max(Q16_MIN, min(Q16_MAX, raw))

def from_q16(q: int) -> float:
    return q / Q16_ONE

def to_q32(x: float) -> int:
    """Convert float to Q32.32 i64, floor-truncated, clamped to i64 range."""
    raw = math.floor(x * Q32_ONE)
    return max(Q32_MIN, min(Q32_MAX, raw))

def from_q32(q: int) -> float:
    return q / Q32_ONE

def clamp_i64(v: int) -> int:
    return max(Q32_MIN, min(Q32_MAX, v))

def emit_header(name: str) -> str:
    return f"""\
// {name} — Q16.16 LUT family, Phase A1.1.
// Auto-generated by tools/gen_luts.py. DO NOT edit by hand.
// Regenerate: python3 tools/gen_luts.py

use std.vec;

"""

# ── 1. recip_q32 (256-entry, domain [1, 256], Q32.32) ─────────────────────────

def gen_recip_q32() -> list[int]:
    """
    256 entries: table[i] = floor(Q32_ONE / (i + 1)) for i in [0, 255].
    Domain: input integer d in [1, 256]; index = d - 1.
    """
    table = []
    for i in range(256):
        d = i + 1
        val = math.floor(Q32_ONE / d)
        table.append(clamp_i64(val))
    return table

# ── 2. exp_q16 (4096-entry, domain [-16, 0], Q16.16) ─────────────────────────

def gen_exp_q16() -> list[int]:
    """
    4096 entries: table[i] = floor(exp(x_i) * Q16_ONE) where
    x_i = -16.0 + i * (16.0 / 4096)  for i in [0, 4095].
    Inputs above 0 saturate to Q16_ONE (exp(0) = 1).
    Inputs below -16 saturate to table[0].
    """
    table = []
    for i in range(4096):
        x = -16.0 + i * (16.0 / 4096)
        if x > 0.0:
            x = 0.0
        val = math.floor(math.exp(x) * Q16_ONE)
        table.append(max(0, min(Q16_MAX, val)))
    return table

# ── 3. tanh_q16 (4096-entry, domain [-8, 8], Q16.16) ──────────────────────────

def gen_tanh_q16() -> list[int]:
    """
    4096 entries: table[i] = floor(tanh(x_i) * Q16_ONE) where
    x_i = -8.0 + i * (16.0 / 4096) for i in [0, 4095].
    Symmetric: tanh(-8) ≈ -1, tanh(8) ≈ 1.
    Saturation: values outside [-8, 8] clamp to table[0] or table[4095].
    """
    table = []
    for i in range(4096):
        x = -8.0 + i * (16.0 / 4096)
        val = math.floor(math.tanh(x) * Q16_ONE)
        table.append(max(Q16_MIN, min(Q16_MAX, val)))
    return table

# ── 4. softmax_q16 — no separate table; composed in .mind ─────────────────────

# ── 5. sqrt_q16 / rsqrt_q16 (2048-entry, domain [ULP, 256], Q16.16) ──────────

def gen_sqrt_q16() -> list[int]:
    """
    2048 entries: table[i] = floor(sqrt(x_i) * Q16_ONE) where
    x_i = (i + 1) * (256.0 / 2048) for i in [0, 2047].
    Entry 0 covers the near-zero bucket [0, 256/2048).
    """
    table = []
    stride = 256.0 / 2048
    for i in range(2048):
        x = (i + 1) * stride
        val = math.floor(math.sqrt(x) * Q16_ONE)
        table.append(max(0, min(Q16_MAX, val)))
    return table

def gen_rsqrt_q16() -> list[int]:
    """
    2048 entries: table[i] = floor(1 / sqrt(x_i) * Q16_ONE) where
    x_i = (i + 1) * (256.0 / 2048) for i in [0, 2047].
    """
    table = []
    stride = 256.0 / 2048
    for i in range(2048):
        x = (i + 1) * stride
        val = math.floor((1.0 / math.sqrt(x)) * Q16_ONE)
        table.append(max(0, min(Q16_MAX, val)))
    return table

# ── MIND source emitters ───────────────────────────────────────────────────────

def emit_store_seq(table: list[int], buf_var: str, indent: str = "    ") -> str:
    """Emit a sequence of __mind_store_i64 calls to populate a buffer."""
    lines = []
    for i, val in enumerate(table):
        lines.append(f"{indent}__mind_store_i64({buf_var} + {i * 8}, {val});")
    return "\n".join(lines)

def write_recip_q32(table: list[int]) -> None:
    n = len(table)  # 256
    stores = emit_store_seq(table, "buf")
    src = emit_header("recip_q32.mind") + f"""\
// recip_q32 — 256-entry Q32.32 reciprocal LUT.
//
// Domain: denominator d in [1, 256] (integer).
// table[i] = floor(Q32_ONE / (i + 1)) for i in [0, 255].
// Q32.32 encoding: 1.0 == 4294967296 (= 1 << 32).
//
// Lookup: recip_q32_lookup(d) returns the Q32.32 reciprocal of integer d.
// If d <= 0 or d > 256, a single Newton step is applied on top of the
// nearest boundary entry to extend coverage gracefully.
//
// Newton refinement (one step, Q32.32 arithmetic):
//   y0 = table entry;  y1 = y0 * (2 - d * y0)  (in Q32.32)
// The refinement is applied only for out-of-domain inputs; in-domain
// inputs use the raw table entry for bit-identical cross-arch results.
//
// Public surface (i64 ABI):
//   recip_q32_init()    -> i64   // allocates and fills the 256-entry buffer;
//                                // returns opaque i64 handle (byte address)
//   recip_q32_lookup(handle: i64, d: i64) -> i64   // Q32.32 result

pub fn recip_q32_init() -> i64 {{
    let buf: i64 = __mind_alloc({n * 8});
{stores}
    buf
}}

// recip_q32_lookup — look up 1/d in Q32.32.
// handle: opaque buffer returned by recip_q32_init().
// d: integer denominator (Q16.16 sum in [1, 256] post softmax accumulation).
// Returns Q32.32 reciprocal.  Out-of-range inputs are clamped to the
// boundary entry — one Newton step is NOT applied here to preserve the
// bit-identical raw-index contract; callers that need higher precision
// outside [1, 256] should use recip_q32_newton(handle, d).
pub fn recip_q32_lookup(handle: i64, d: i64) -> i64 {{
    if d <= 0 {{ return __mind_load_i64(handle); }}
    if d > 256 {{
        let last_off: i64 = 255 * 8;
        return __mind_load_i64(handle + last_off);
    }}
    let idx: i64 = (d - 1) * 8;
    __mind_load_i64(handle + idx)
}}

// recip_q32_newton — one Newton refinement step on a Q32.32 seed.
// Used for out-of-domain inputs where the raw table entry is too coarse.
// Step: y1 = y0 * (2 - d * y0) in Q32.32.
// The multiply (d * y0) is done in i64 with a >>32 shift to stay in Q32.32.
pub fn recip_q32_newton(handle: i64, d: i64) -> i64 {{
    let y0: i64 = recip_q32_lookup(handle, d);
    // d * y0 in Q32.32: d is a Q16.16 integer times Q32_ONE-scaled y0
    // Both are i64; product needs a >>32 shift.  Use i64 arithmetic.
    let dy: i64 = (d * y0) >> 32;
    let two_q32: i64 = 8589934592;
    let correction: i64 = two_q32 - dy;
    (y0 * correction) >> 32
}}

// recip_q32_free — release the buffer.
pub fn recip_q32_free(handle: i64) -> i64 {{
    __mind_free(handle);
    0
}}
"""
    path = os.path.join(LUTS_DIR, "recip_q32.mind")
    with open(path, "w") as f:
        f.write(src)
    print(f"wrote {path}  ({n} entries, {len(src)} chars)")


def write_exp_q16(table: list[int]) -> None:
    n = len(table)  # 4096
    # Split init into two halves to keep function size manageable
    half = n // 2
    stores_lo = emit_store_seq(table[:half], "buf")
    stores_hi = emit_store_seq(table[half:], "buf", indent="    ")
    # Offset second half by half*8
    stores_hi_lines = []
    for i, val in enumerate(table[half:]):
        stores_hi_lines.append(f"    __mind_store_i64(buf + {(half + i) * 8}, {val});")
    stores_hi = "\n".join(stores_hi_lines)

    src = emit_header("exp_q16.mind") + f"""\
// exp_q16 — 4096-entry Q16.16 exp LUT.
//
// Domain: x in [-16.0, 0.0] (Q16.16 input values).
// table[i] = floor(exp(x_i) * Q16_ONE) where
//   x_i = -16.0 + i * (16.0 / 4096)
// Entry 0 corresponds to x = -16.0 (exp ≈ 1.1e-7, rounds to 7 in Q16.16).
// Entry 4095 corresponds to x = 0.0 (exp = 1.0 = 65536 in Q16.16).
//
// Inputs above 0 saturate to Q16_ONE (65536).
// Inputs below -16.0 saturate to table[0].
//
// Stride in Q16.16 input units: 16.0 * Q16_ONE / 4096 = 256.
//
// Public surface (i64 ABI):
//   exp_q16_init()   -> i64  // allocate + fill; returns handle
//   exp_q16_lookup(handle: i64, x: i64) -> i64  // Q16.16 result

// Q16.16 constants (inlined to avoid cross-module deps in stand-alone parse).
// Q16_ONE = 65536, Q16_EXP_DOMAIN_LO = -16 * 65536 = -1048576
// stride = 16 * 65536 / 4096 = 256

pub fn exp_q16_init() -> i64 {{
    let buf: i64 = __mind_alloc({n * 8});
{stores_lo}
{stores_hi}
    buf
}}

pub fn exp_q16_lookup(handle: i64, x: i64) -> i64 {{
    let q16_one: i64 = 65536;
    let domain_lo: i64 = -1048576;
    let stride: i64 = 256;
    if x >= 0 {{ return q16_one; }}
    if x <= domain_lo {{ return __mind_load_i64(handle); }}
    let shifted: i64 = x - domain_lo;
    let idx: i64 = shifted / stride;
    if idx < 0 {{ return __mind_load_i64(handle); }}
    if idx >= 4096 {{ return q16_one; }}
    __mind_load_i64(handle + idx * 8)
}}

pub fn exp_q16_free(handle: i64) -> i64 {{
    __mind_free(handle);
    0
}}
"""
    path = os.path.join(LUTS_DIR, "exp_q16.mind")
    with open(path, "w") as f:
        f.write(src)
    print(f"wrote {path}  ({n} entries, {len(src)} chars)")


def write_tanh_q16(table: list[int]) -> None:
    n = len(table)  # 4096
    stores_lo = emit_store_seq(table[:2048], "buf")
    stores_hi_lines = []
    for i, val in enumerate(table[2048:]):
        stores_hi_lines.append(f"    __mind_store_i64(buf + {(2048 + i) * 8}, {val});")
    stores_hi = "\n".join(stores_hi_lines)

    src = emit_header("tanh_q16.mind") + f"""\
// tanh_q16 — 4096-entry Q16.16 tanh LUT.
//
// Domain: x in [-8.0, 8.0] (Q16.16 input values).
// table[i] = floor(tanh(x_i) * Q16_ONE) where
//   x_i = -8.0 + i * (16.0 / 4096)
// Entry 0: x = -8.0, tanh ≈ -1.0 (stored as -65536).
// Entry 4095: x ≈ +8.0, tanh ≈ +1.0 (stored as +65536).
//
// Inputs <= -8.0 saturate to table[0].
// Inputs >= +8.0 saturate to table[4095].
//
// Stride in Q16.16 input units: 16.0 * Q16_ONE / 4096 = 256.
// Domain half-width in Q16.16: 8.0 * Q16_ONE = 524288.
//
// Derived from tanh(x) = 1 - 2/(exp(2x)+1) which uses exp_q16 at
// build time; the resulting i64 values are bit-exact at runtime.
//
// Public surface (i64 ABI):
//   tanh_q16_init()  -> i64
//   tanh_q16_lookup(handle: i64, x: i64) -> i64

pub fn tanh_q16_init() -> i64 {{
    let buf: i64 = __mind_alloc({n * 8});
{stores_lo}
{stores_hi}
    buf
}}

pub fn tanh_q16_lookup(handle: i64, x: i64) -> i64 {{
    let domain_lo: i64 = -524288;
    let domain_hi: i64 = 524288;
    let stride: i64 = 256;
    if x <= domain_lo {{ return __mind_load_i64(handle); }}
    if x >= domain_hi {{
        let last_off: i64 = 4095 * 8;
        return __mind_load_i64(handle + last_off);
    }}
    let shifted: i64 = x - domain_lo;
    let idx: i64 = shifted / stride;
    if idx < 0 {{ return __mind_load_i64(handle); }}
    if idx >= 4096 {{
        let last_off: i64 = 4095 * 8;
        return __mind_load_i64(handle + last_off);
    }}
    __mind_load_i64(handle + idx * 8)
}}

pub fn tanh_q16_free(handle: i64) -> i64 {{
    __mind_free(handle);
    0
}}
"""
    path = os.path.join(LUTS_DIR, "tanh_q16.mind")
    with open(path, "w") as f:
        f.write(src)
    print(f"wrote {path}  ({n} entries, {len(src)} chars)")


def write_softmax_q16() -> None:
    src = emit_header("softmax_q16.mind") + """\
// softmax_q16 — Q16.16 softmax kernel.
//
// Implements the 5-stage pinned pipeline from spec/numerics.md §5 and
// encoder-port-audit-2026-05-18.md §3.1:
//
//   Stage 1: find m = max(x_i) in Q16.16  (sequential, ascending index)
//   Stage 2: y_i = exp_q16(x_i - m)       (elementwise; uses exp_q16 LUT)
//   Stage 3: D = sum(y_i)                  (Q32.32 accumulator, ascending)
//   Stage 4: r = recip_q32(D)              (uses recip_q32 LUT)
//   Stage 5: out_i = y_i * r               (Q16.16 multiply, narrowing)
//
// Cross-arch identity: every stage uses only LUT lookups and integer
// arithmetic; no FMA-introducing interpolation anywhere.
//
// Public surface (i64 ABI):
//   softmax_q16_run(exp_h: i64, recip_h: i64, buf: i64, n: i64) -> i64
//
//   exp_h   : handle from exp_q16_init()
//   recip_h : handle from recip_q32_init()
//   buf     : i64 pointer to n Q16.16 values (input on entry; output on return)
//   n       : number of elements
//
// Returns 0 on success.  Output is written back into buf in-place.
// The caller owns all memory.

// ── Stage 1 helper: find max (tail-recursive, ascending index) ───────────────

pub fn softmax_max_step(buf: i64, n: i64, idx: i64, acc: i64) -> i64 {
    if idx >= n { return acc; }
    let v: i64 = __mind_load_i64(buf + idx * 8);
    if v > acc {
        return softmax_max_step(buf, n, idx + 1, v);
    }
    softmax_max_step(buf, n, idx + 1, acc)
}

// ── Stage 2 + 3 helper: subtract max, apply exp, accumulate sum ──────────────
// Returns Q32.32 sum D.  Writes y_i back into buf[i] as Q16.16.

pub fn softmax_exp_sum_step(exp_h: i64, buf: i64, n: i64, idx: i64, m: i64, acc_q32: i64) -> i64 {
    if idx >= n { return acc_q32; }
    let xi: i64 = __mind_load_i64(buf + idx * 8);
    let shifted: i64 = xi - m;
    let yi: i64 = exp_q16_lookup(exp_h, shifted);
    __mind_store_i64(buf + idx * 8, yi);
    // Widen yi (Q16.16) to Q32.32 by left-shifting 16.
    let yi_q32: i64 = yi << 16;
    let new_acc: i64 = acc_q32 + yi_q32;
    softmax_exp_sum_step(exp_h, buf, n, idx + 1, m, new_acc)
}

// ── Stage 5 helper: multiply each y_i by 1/D (Q16.16 × Q32.32 -> Q16.16) ────

pub fn softmax_scale_step(recip_h: i64, buf: i64, n: i64, idx: i64, d_int: i64) -> i64 {
    if idx >= n { return 0; }
    let yi: i64 = __mind_load_i64(buf + idx * 8);
    let r: i64 = recip_q32_lookup(recip_h, d_int);
    // yi (Q16.16) * r (Q32.32) -> shift right 32 to get Q16.16 result.
    let prod: i64 = (yi * r) >> 32;
    let q16_max: i64 = 2147483647;
    let q16_min: i64 = -2147483648;
    let clamped: i64 = if prod > q16_max {
        q16_max
    } else {
        if prod < q16_min { q16_min } else { prod }
    };
    __mind_store_i64(buf + idx * 8, clamped);
    softmax_scale_step(recip_h, buf, n, idx + 1, d_int)
}

// ── Top-level softmax kernel ──────────────────────────────────────────────────

pub fn softmax_q16_run(exp_h: i64, recip_h: i64, buf: i64, n: i64) -> i64 {
    if n <= 0 { return 0; }

    // Stage 1: find max.  Seed with first element.
    let first: i64 = __mind_load_i64(buf);
    let m: i64 = softmax_max_step(buf, n, 1, first);

    // Stages 2 + 3: exp(x - m) and sum into Q32.32 accumulator.
    let d_q32: i64 = softmax_exp_sum_step(exp_h, buf, n, 0, m, 0);

    // Stage 4: integer denominator for recip_q32 LUT.
    // D is a Q32.32 integer; convert to integer units (>= 1).
    // D_int = ceil(d_q32 / Q32_ONE) — use right shift 32 then clamp to [1, 256].
    let d_shifted: i64 = d_q32 >> 32;
    let d_int: i64 = if d_shifted < 1 {
        1
    } else {
        if d_shifted > 256 { 256 } else { d_shifted }
    };

    // Stage 5: scale each y_i by 1/D.
    softmax_scale_step(recip_h, buf, n, 0, d_int)
}
"""
    path = os.path.join(LUTS_DIR, "softmax_q16.mind")
    with open(path, "w") as f:
        f.write(src)
    print(f"wrote {path}")


def write_sqrt_q16(sqrt_table: list[int], rsqrt_table: list[int]) -> None:
    n = len(sqrt_table)   # 2048
    assert len(rsqrt_table) == n

    stores_sqrt_lo = emit_store_seq(sqrt_table[:1024], "sqrt_buf")
    stores_sqrt_hi_lines = []
    for i, val in enumerate(sqrt_table[1024:]):
        stores_sqrt_hi_lines.append(f"    __mind_store_i64(sqrt_buf + {(1024 + i) * 8}, {val});")
    stores_sqrt_hi = "\n".join(stores_sqrt_hi_lines)

    stores_rsqrt_lo = emit_store_seq(rsqrt_table[:1024], "rsqrt_buf")
    stores_rsqrt_hi_lines = []
    for i, val in enumerate(rsqrt_table[1024:]):
        stores_rsqrt_hi_lines.append(f"    __mind_store_i64(rsqrt_buf + {(1024 + i) * 8}, {val});")
    stores_rsqrt_hi = "\n".join(stores_rsqrt_hi_lines)

    src = emit_header("sqrt_q16.mind") + f"""\
// sqrt_q16 / rsqrt_q16 — 2048-entry Q16.16 sqrt and rsqrt LUTs.
//
// Domain: x in [ULP, 256.0] (Q16.16 input values, ULP = 1).
// Stride: 256.0 * Q16_ONE / 2048 = 8192 (Q16.16 units per entry).
//
// sqrt_table[i] = floor(sqrt(x_i) * Q16_ONE)
// rsqrt_table[i] = floor(1/sqrt(x_i) * Q16_ONE)
//   where x_i = (i + 1) * stride / Q16_ONE  (real units)
//   i.e. x_i = (i + 1) * (256.0 / 2048)
//
// Inputs x <= 0 return MAX_Q16_16 (sentinel) for rsqrt,
// and 0 for sqrt.
// Inputs x > 256.0 clamp to table[2047].
//
// One Newton step (seed from LUT) is available via sqrt_q16_newton /
// rsqrt_q16_newton for callers that need finer accuracy outside the table.
//
// The struct SqrtHandles carries both buffer pointers as a single i64-pair
// encoded as: hi32 = rsqrt handle index / lo32 = sqrt handle index.
// Callers should store the two handles separately.
//
// Public surface (i64 ABI):
//   sqrt_q16_init()   -> i64  // sqrt table handle
//   rsqrt_q16_init()  -> i64  // rsqrt table handle
//   sqrt_q16_lookup(handle: i64, x: i64) -> i64
//   rsqrt_q16_lookup(handle: i64, x: i64) -> i64
//   sqrt_q16_free(handle: i64)  -> i64
//   rsqrt_q16_free(handle: i64) -> i64

// Stride in Q16.16 units: (256 * 65536) / 2048 = 8192.
// Q16_ONE = 65536, Q16_MAX = 2147483647.

pub fn sqrt_q16_init() -> i64 {{
    let sqrt_buf: i64 = __mind_alloc({n * 8});
{stores_sqrt_lo}
{stores_sqrt_hi}
    sqrt_buf
}}

pub fn rsqrt_q16_init() -> i64 {{
    let rsqrt_buf: i64 = __mind_alloc({n * 8});
{stores_rsqrt_lo}
{stores_rsqrt_hi}
    rsqrt_buf
}}

pub fn sqrt_q16_lookup(handle: i64, x: i64) -> i64 {{
    let q16_max: i64 = 2147483647;
    let stride: i64 = 8192;
    let domain_hi_q16: i64 = 16777216;
    if x <= 0 {{ return 0; }}
    if x >= domain_hi_q16 {{
        let last_off: i64 = 2047 * 8;
        return __mind_load_i64(handle + last_off);
    }}
    let idx: i64 = (x - 1) / stride;
    if idx >= 2048 {{
        let last_off: i64 = 2047 * 8;
        return __mind_load_i64(handle + last_off);
    }}
    __mind_load_i64(handle + idx * 8)
}}

pub fn rsqrt_q16_lookup(handle: i64, x: i64) -> i64 {{
    let q16_max: i64 = 2147483647;
    let stride: i64 = 8192;
    let domain_hi_q16: i64 = 16777216;
    if x <= 0 {{ return q16_max; }}
    if x >= domain_hi_q16 {{
        let last_off: i64 = 2047 * 8;
        return __mind_load_i64(handle + last_off);
    }}
    let idx: i64 = (x - 1) / stride;
    if idx >= 2048 {{
        let last_off: i64 = 2047 * 8;
        return __mind_load_i64(handle + last_off);
    }}
    __mind_load_i64(handle + idx * 8)
}}

// sqrt Newton step: y_{n+1} = (y_n + x/y_n) / 2  (in Q16.16).
// Applied once to the LUT seed to tighten accuracy.
pub fn sqrt_q16_newton(handle: i64, x: i64) -> i64 {{
    let y0: i64 = sqrt_q16_lookup(handle, x);
    if y0 <= 0 {{ return 0; }}
    let q16_one: i64 = 65536;
    let q16_max: i64 = 2147483647;
    // x/y0 in Q16.16: x * Q16_ONE / y0
    let xq: i64 = (x * q16_one) / y0;
    let y1: i64 = (y0 + xq) / 2;
    if y1 > q16_max {{ return q16_max; }}
    y1
}}

// rsqrt Newton step: y_{n+1} = y_n * (3 - x * y_n^2) / 2  (in Q16.16).
pub fn rsqrt_q16_newton(handle: i64, x: i64) -> i64 {{
    let y0: i64 = rsqrt_q16_lookup(handle, x);
    let q16_one: i64 = 65536;
    let q16_max: i64 = 2147483647;
    // y0^2 in Q16.16: (y0 * y0) >> 16
    let yy: i64 = (y0 * y0) >> 16;
    // x * yy in Q16.16: (x * yy) >> 16
    let xyy: i64 = (x * yy) >> 16;
    // 3 - xyy in Q16.16
    let three_q16: i64 = 196608;
    let inner: i64 = three_q16 - xyy;
    // y0 * inner / 2 in Q16.16: (y0 * inner) >> 17
    let y1: i64 = (y0 * inner) >> 17;
    if y1 > q16_max {{ return q16_max; }}
    if y1 < 0 {{ return 0; }}
    y1
}}

pub fn sqrt_q16_free(handle: i64) -> i64 {{
    __mind_free(handle);
    0
}}

pub fn rsqrt_q16_free(handle: i64) -> i64 {{
    __mind_free(handle);
    0
}}
"""
    path = os.path.join(LUTS_DIR, "sqrt_q16.mind")
    with open(path, "w") as f:
        f.write(src)
    print(f"wrote {path}  ({n} entries sqrt+rsqrt, {len(src)} chars)")


# ── smoke test fixture ─────────────────────────────────────────────────────────

def gen_smoke_fixture(
    recip_table: list[int],
    exp_table: list[int],
    tanh_table: list[int],
    sqrt_table: list[int],
    rsqrt_table: list[int],
    n_samples: int = 32,
    rng_seed: int = 0xC0FFEE_A1B2C3D4,
) -> None:
    """
    Generate tests/luts_smoke.mind: a MIND smoke-test that verifies
    <= 1 ULP-eq error on a fixed set of reference points per LUT.

    Strategy: bake (input, expected_output) pairs as literal constants
    in the test function, then assert abs(lookup(input) - expected) <= 1.

    We use a subset of n_samples points per LUT drawn from a fixed RNG
    sequence so the fixture is fully deterministic.
    """
    rng = random.Random(rng_seed)

    # ── recip_q32 samples: d in [1, 256] ──────────────────────────────────────
    recip_samples = []
    for _ in range(n_samples):
        d = rng.randint(1, 256)
        expected = recip_table[d - 1]
        recip_samples.append((d, expected))

    # ── exp_q16 samples: x in [-16.0, 0.0] Q16.16 ────────────────────────────
    exp_samples = []
    for _ in range(n_samples):
        i = rng.randint(0, 4095)
        x_q16 = -1048576 + i * 256   # domain_lo + i * stride
        expected = exp_table[i]
        exp_samples.append((x_q16, expected))

    # ── tanh_q16 samples: x in [-8.0, 8.0] Q16.16 ────────────────────────────
    tanh_samples = []
    for _ in range(n_samples):
        i = rng.randint(0, 4095)
        x_q16 = -524288 + i * 256   # domain_lo + i * stride
        expected = tanh_table[i]
        tanh_samples.append((x_q16, expected))

    # ── sqrt_q16 samples: x in [1, 16777216] Q16.16 ──────────────────────────
    sqrt_samples = []
    for _ in range(n_samples):
        i = rng.randint(0, 2047)
        x_q16 = (i + 1) * 8192   # (i+1) * stride in Q16.16
        expected_sqrt = sqrt_table[i]
        expected_rsqrt = rsqrt_table[i]
        sqrt_samples.append((x_q16, expected_sqrt, expected_rsqrt))

    def emit_recip_checks(samples: list) -> str:
        lines = []
        for d, exp in samples:
            lines.append(f"    let r_{d}: i64 = recip_q32_lookup(rh, {d});")
            lines.append(f"    let diff_{d}: i64 = r_{d} - {exp};")
            lines.append(f"    let adiff_{d}: i64 = if diff_{d} < 0 {{ 0 - diff_{d} }} else {{ diff_{d} }};")
            lines.append(f"    if adiff_{d} > 1 {{ return {d}; }}")
        return "\n".join(lines)

    def emit_exp_checks(samples: list) -> str:
        lines = []
        for idx, (x, exp) in enumerate(samples):
            lines.append(f"    let ex_{idx}: i64 = exp_q16_lookup(eh, {x});")
            lines.append(f"    let ediff_{idx}: i64 = ex_{idx} - {exp};")
            lines.append(f"    let eadiff_{idx}: i64 = if ediff_{idx} < 0 {{ 0 - ediff_{idx} }} else {{ ediff_{idx} }};")
            lines.append(f"    if eadiff_{idx} > 1 {{ return {x}; }}")
        return "\n".join(lines)

    def emit_tanh_checks(samples: list) -> str:
        lines = []
        for idx, (x, exp) in enumerate(samples):
            lines.append(f"    let tx_{idx}: i64 = tanh_q16_lookup(th, {x});")
            lines.append(f"    let tdiff_{idx}: i64 = tx_{idx} - {exp};")
            lines.append(f"    let tadiff_{idx}: i64 = if tdiff_{idx} < 0 {{ 0 - tdiff_{idx} }} else {{ tdiff_{idx} }};")
            lines.append(f"    if tadiff_{idx} > 1 {{ return {x}; }}")
        return "\n".join(lines)

    def emit_sqrt_checks(samples: list) -> str:
        lines = []
        for idx, (x, esq, erq) in enumerate(samples):
            lines.append(f"    let sqx_{idx}: i64 = sqrt_q16_lookup(sh, {x});")
            lines.append(f"    let sqdiff_{idx}: i64 = sqx_{idx} - {esq};")
            lines.append(f"    let sqadiff_{idx}: i64 = if sqdiff_{idx} < 0 {{ 0 - sqdiff_{idx} }} else {{ sqdiff_{idx} }};")
            lines.append(f"    if sqadiff_{idx} > 1 {{ return {x}; }}")
            lines.append(f"    let rsqx_{idx}: i64 = rsqrt_q16_lookup(rsh, {x});")
            lines.append(f"    let rsqdiff_{idx}: i64 = rsqx_{idx} - {erq};")
            lines.append(f"    let rsqadiff_{idx}: i64 = if rsqdiff_{idx} < 0 {{ 0 - rsqdiff_{idx} }} else {{ rsqdiff_{idx} }};")
            lines.append(f"    if rsqadiff_{idx} > 1 {{ return {x}; }}")
        return "\n".join(lines)

    src = """\
// tests/luts_smoke.mind — LUT family smoke tests.
// Auto-generated by tools/gen_luts.py. DO NOT edit by hand.
//
// Each test function allocates the relevant LUT, checks a fixed set of
// (input, expected_output) pairs with <= 1 ULP-eq tolerance, then frees
// the LUT.  Returns 0 on pass; returns the failing input on error.

use std.vec;

// ── Smoke test: recip_q32 ─────────────────────────────────────────────────────
// Checks """ + str(n_samples) + """ fixed (d, expected_Q32.32) pairs.
// Returns 0 on pass; returns failing d on first mismatch.
pub fn smoke_recip_q32() -> i64 {
    let rh: i64 = recip_q32_init();
""" + emit_recip_checks(recip_samples) + """
    recip_q32_free(rh);
    0
}

// ── Smoke test: exp_q16 ───────────────────────────────────────────────────────
// Checks """ + str(n_samples) + """ fixed (x_Q16, expected_Q16) pairs.
// Returns 0 on pass; returns failing x on first mismatch.
pub fn smoke_exp_q16() -> i64 {
    let eh: i64 = exp_q16_init();
""" + emit_exp_checks(exp_samples) + """
    exp_q16_free(eh);
    0
}

// ── Smoke test: tanh_q16 ─────────────────────────────────────────────────────
// Checks """ + str(n_samples) + """ fixed (x_Q16, expected_Q16) pairs.
// Returns 0 on pass; returns failing x on first mismatch.
pub fn smoke_tanh_q16() -> i64 {
    let th: i64 = tanh_q16_init();
""" + emit_tanh_checks(tanh_samples) + """
    tanh_q16_free(th);
    0
}

// ── Smoke test: softmax_q16 ───────────────────────────────────────────────────
// Verifies that softmax_q16_run on a uniform 4-element input produces
// approximately uniform output (each element ~ Q16_ONE/4 = 16384).
// Tolerance: <= 2 ULP (1 from exp rounding, 1 from recip rounding).
pub fn smoke_softmax_q16() -> i64 {
    let eh: i64 = exp_q16_init();
    let rh: i64 = recip_q32_init();
    let buf: i64 = __mind_alloc(32);
    let q16_one: i64 = 65536;
    __mind_store_i64(buf + 0, q16_one);
    __mind_store_i64(buf + 8, q16_one);
    __mind_store_i64(buf + 16, q16_one);
    __mind_store_i64(buf + 24, q16_one);
    let rc: i64 = softmax_q16_run(eh, rh, buf, 4);
    let expected: i64 = 16384;
    let v0: i64 = __mind_load_i64(buf);
    let v1: i64 = __mind_load_i64(buf + 8);
    let v2: i64 = __mind_load_i64(buf + 16);
    let v3: i64 = __mind_load_i64(buf + 24);
    let d0: i64 = v0 - expected;
    let a0: i64 = if d0 < 0 { 0 - d0 } else { d0 };
    let d1: i64 = v1 - expected;
    let a1: i64 = if d1 < 0 { 0 - d1 } else { d1 };
    let d2: i64 = v2 - expected;
    let a2: i64 = if d2 < 0 { 0 - d2 } else { d2 };
    let d3: i64 = v3 - expected;
    let a3: i64 = if d3 < 0 { 0 - d3 } else { d3 };
    __mind_free(buf);
    exp_q16_free(eh);
    recip_q32_free(rh);
    if a0 > 2 { return 1; }
    if a1 > 2 { return 2; }
    if a2 > 2 { return 3; }
    if a3 > 2 { return 4; }
    0
}

// ── Smoke test: sqrt_q16 / rsqrt_q16 ─────────────────────────────────────────
// Checks """ + str(n_samples) + """ fixed (x_Q16, expected_sqrt, expected_rsqrt) triples.
// Returns 0 on pass; returns failing x on first mismatch.
pub fn smoke_sqrt_q16() -> i64 {
    let sh: i64 = sqrt_q16_init();
    let rsh: i64 = rsqrt_q16_init();
""" + emit_sqrt_checks(sqrt_samples) + """
    sqrt_q16_free(sh);
    rsqrt_q16_free(rsh);
    0
}

// ── Top-level runner ──────────────────────────────────────────────────────────
// Returns 0 if all smoke tests pass; nonzero on first failure.
pub fn run_all_smoke_tests() -> i64 {
    let r1: i64 = smoke_recip_q32();
    if r1 != 0 { return r1; }
    let r2: i64 = smoke_exp_q16();
    if r2 != 0 { return r2; }
    let r3: i64 = smoke_tanh_q16();
    if r3 != 0 { return r3; }
    let r4: i64 = smoke_softmax_q16();
    if r4 != 0 { return r4; }
    let r5: i64 = smoke_sqrt_q16();
    if r5 != 0 { return r5; }
    0
}
"""
    path = os.path.join(TESTS_DIR, "luts_smoke.mind")
    with open(path, "w") as f:
        f.write(src)
    print(f"wrote {path}  ({n_samples} samples/LUT)")


# ── validation ─────────────────────────────────────────────────────────────────

def validate_tables(
    recip_table: list[int],
    exp_table: list[int],
    tanh_table: list[int],
    sqrt_table: list[int],
    rsqrt_table: list[int],
) -> None:
    """Quick ULP-error check on each table against float64 reference."""
    errors = []

    # recip_q32: relative error in Q32.32 units
    for i, val in enumerate(recip_table):
        d = i + 1
        ref = Q32_ONE / d
        ref_floor = math.floor(ref)
        err = abs(val - ref_floor)
        if err > 1:
            errors.append(f"recip_q32[{i}]: val={val} ref_floor={ref_floor} err={err}")

    # exp_q16: ULP error
    for i, val in enumerate(exp_table):
        x = -16.0 + i * (16.0 / 4096)
        ref = math.floor(math.exp(x) * Q16_ONE)
        ref_clamped = max(0, min(Q16_MAX, ref))
        err = abs(val - ref_clamped)
        if err > 1:
            errors.append(f"exp_q16[{i}]: val={val} ref={ref_clamped} err={err}")

    # tanh_q16
    for i, val in enumerate(tanh_table):
        x = -8.0 + i * (16.0 / 4096)
        ref = math.floor(math.tanh(x) * Q16_ONE)
        ref_clamped = max(Q16_MIN, min(Q16_MAX, ref))
        err = abs(val - ref_clamped)
        if err > 1:
            errors.append(f"tanh_q16[{i}]: val={val} ref={ref_clamped} err={err}")

    # sqrt_q16
    stride = 256.0 / 2048
    for i, val in enumerate(sqrt_table):
        x = (i + 1) * stride
        ref = math.floor(math.sqrt(x) * Q16_ONE)
        ref_clamped = max(0, min(Q16_MAX, ref))
        err = abs(val - ref_clamped)
        if err > 1:
            errors.append(f"sqrt_q16[{i}]: val={val} ref={ref_clamped} err={err}")

    # rsqrt_q16
    for i, val in enumerate(rsqrt_table):
        x = (i + 1) * stride
        ref = math.floor((1.0 / math.sqrt(x)) * Q16_ONE)
        ref_clamped = max(0, min(Q16_MAX, ref))
        err = abs(val - ref_clamped)
        if err > 1:
            errors.append(f"rsqrt_q16[{i}]: val={val} ref={ref_clamped} err={err}")

    if errors:
        print("VALIDATION FAILURES:")
        for e in errors[:20]:
            print("  ", e)
        raise RuntimeError(f"{len(errors)} validation failures")
    else:
        print("all tables validated: 0 ULP errors (floor-truncation is exact)")


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    print("generating LUT tables...")
    recip_table = gen_recip_q32()
    exp_table   = gen_exp_q16()
    tanh_table  = gen_tanh_q16()
    sqrt_table  = gen_sqrt_q16()
    rsqrt_table = gen_rsqrt_q16()

    print("validating tables...")
    validate_tables(recip_table, exp_table, tanh_table, sqrt_table, rsqrt_table)

    print("writing MIND source files...")
    write_recip_q32(recip_table)
    write_exp_q16(exp_table)
    write_tanh_q16(tanh_table)
    write_softmax_q16()
    write_sqrt_q16(sqrt_table, rsqrt_table)

    print("writing smoke test fixture...")
    gen_smoke_fixture(recip_table, exp_table, tanh_table, sqrt_table, rsqrt_table)

    print("done.")


if __name__ == "__main__":
    main()
